
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class categorypanel extends javax.swing.JPanel {

    /**
     * Creates new form categorypanel
     */
    public categorypanel() {
        initComponents();
        setSize(800,400);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcategoryname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setLayout(null);

        lbcategoryname.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        lbcategoryname.setForeground(new java.awt.Color(51, 51, 51));
        lbcategoryname.setText("jLabel1");
        add(lbcategoryname);
        lbcategoryname.setBounds(10, 10, 780, 60);

        mainpanel.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 770, 150);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbcategoryname;
    public javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
