
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        tfusername.setText(GlobalData.nameofuser);
        tfusername.setEnabled(false);
        setSize(600,600);
        getContentPane().setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfusername = new javax.swing.JTextField();
        tfoldpassword = new javax.swing.JTextField();
        pfconfirmpassword = new javax.swing.JPasswordField();
        tfnewpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("ConfirmPassword");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 230, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("OldPassword");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 170, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("NewPassword");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 180, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 340, 170, 50);
        getContentPane().add(tfusername);
        tfusername.setBounds(270, 60, 220, 30);
        getContentPane().add(tfoldpassword);
        tfoldpassword.setBounds(270, 112, 220, 30);
        getContentPane().add(pfconfirmpassword);
        pfconfirmpassword.setBounds(270, 230, 220, 30);
        getContentPane().add(tfnewpassword);
        tfnewpassword.setBounds(270, 170, 220, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Change  Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 10, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
            String oldpassword  = tfoldpassword.getText();
            String NewPassword = tfnewpassword.getText();
            String ConfirmPassword = pfconfirmpassword.getText();
                      System.out.println("newPassword "+NewPassword+" and oldpassword is "+oldpassword);
            if(ConfirmPassword.equals(NewPassword)){
        try {
            
            
            HttpResponse<String> response = Unirest.get(GlobalData.hostname + "/UserChangePassword")
                    .queryString("Username", GlobalData.nameofuser)
                    .queryString("OldPassword",oldpassword)
                    .queryString("NewPassword",NewPassword)
                   
                    .asString();
            String ans = response.getBody();
            
            if(ans.equals("successfully Update!!!!!!!!!!!!!!!")){
                new userlogin().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this,ans);
            }
        } catch (UnirestException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
else{
                JOptionPane.showMessageDialog(this, "newpassword and confirm Password should be match!!!1");
            }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pfconfirmpassword;
    private javax.swing.JPasswordField tfnewpassword;
    private javax.swing.JTextField tfoldpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
