/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class roomspanel extends javax.swing.JPanel {

    /**
     * Creates new form roomspanel
     */
    public roomspanel() {
        initComponents();
        setSize(200,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbpreview = new javax.swing.JLabel();
        lbroomname = new javax.swing.JLabel();

        setLayout(null);

        lbpreview.setText("jLabel1");
        add(lbpreview);
        lbpreview.setBounds(11, 16, 170, 110);

        lbroomname.setText("jLabel2");
        add(lbroomname);
        lbroomname.setBounds(10, 150, 180, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbpreview;
    public javax.swing.JLabel lbroomname;
    // End of variables declaration//GEN-END:variables
}
