
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class userSignUp extends javax.swing.JFrame {

    File file;

    public userSignUp() {
        initComponents();
        setLocation(100, 100);
        setSize(1000, 900);
        cb1.removeAllItems();
        cb1.addItem("---select Items---");
        cb1.addItem("Male");
        cb1.addItem("Female");
        getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pfpassword = new javax.swing.JPasswordField();
        tfdisplayname = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox<>();
        tfemail = new javax.swing.JTextField();
        tfmobile = new javax.swing.JTextField();
        lbphoto = new javax.swing.JLabel();
        pfconfirm = new javax.swing.JPasswordField();
        btbrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("User SignUp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 180, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Photo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 510, 150, 40);
        getContentPane().add(tfusername);
        tfusername.setBounds(260, 120, 210, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 150, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 240, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Display Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 300, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 360, 150, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Mobile number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 460, 150, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 410, 150, 40);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 680, 140, 50);
        getContentPane().add(pfpassword);
        pfpassword.setBounds(260, 180, 210, 40);
        getContentPane().add(tfdisplayname);
        tfdisplayname.setBounds(260, 302, 210, 40);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(260, 360, 210, 30);

        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });
        getContentPane().add(tfemail);
        tfemail.setBounds(259, 412, 210, 40);
        getContentPane().add(tfmobile);
        tfmobile.setBounds(260, 462, 210, 40);

        lbphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbphoto);
        lbphoto.setBounds(260, 520, 210, 140);

        pfconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfconfirmActionPerformed(evt);
            }
        });
        getContentPane().add(pfconfirm);
        pfconfirm.setBounds(260, 240, 210, 40);

        btbrowse.setText("browse");
        btbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btbrowse);
        btbrowse.setBounds(490, 630, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String UserName = tfusername.getText();
        String Password = pfpassword.getText();
        String Confirm = pfconfirm.getText();
        String DisplayName = tfdisplayname.getText();
        String Gender = (String) cb1.getSelectedItem();
        String Email = tfemail.getText();
        String Phone = tfmobile.getText();
        System.out.println(UserName +" "+Password+" "+DisplayName+" "+Gender+" "+file+" "+Email+" "+" "+Phone+" ");

        if (UserName.equals("") || Password.equals("") || Confirm.equals("") || DisplayName.equals("") || Gender.equals("") || Email.equals("") || Phone.equals("") || file == null) {
            JOptionPane.showMessageDialog(this, "All fields are required");
        } else if (!(Password.equals(Confirm))) {
            JOptionPane.showMessageDialog(this, "password and confirm password should be same ");
        } else if (Phone.length() != 10) {
            JOptionPane.showMessageDialog(this, "mobile number invalid !!!");

        } 
        else if (!(Email.contains("@")) || !(Email.contains("."))) {
            JOptionPane.showMessageDialog(this, "invalid Email Id");
        } 
        else if (Gender.equals("---select Items---")) {
            JOptionPane.showMessageDialog(this, "select your gender!!!!!!!!");
        }
        else {
            try {
                HttpResponse<String> response = Unirest.post(GlobalData.hostname + "/AddUser")
                        .queryString("un", UserName)
                        .queryString("ps", Password)
                        .queryString("dn", DisplayName)
                        .queryString("gen", Gender)
                        .queryString("pn", Phone)
                        .queryString("e", Email)
                        .field("Photo", file)
                        .asString();

                JOptionPane.showMessageDialog(this, response.getBody());
            } catch (UnirestException ex) {
                Logger.getLogger(AddRooms.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void pfconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfconfirmActionPerformed

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void btbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbrowseActionPerformed

        JFileChooser jfc = new JFileChooser("C:\\");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpeg", "jpg", "bmp", "png");// to seclect only specific formate file
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);  //tp set enable to other filter 
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            try {
                BufferedImage img = ImageIO.read(file);
                //Image newimg = img.getScaledInstance(lbpreview.getWidth(), lbpreview.getHeight(), Image.SCALE_SMOOTH);
                BufferedImage newimg = resizephoto(img, lbphoto.getWidth(), lbphoto.getHeight());
//                lbfilename.setText(file.getName());
                lbphoto.setIcon(new ImageIcon(newimg));
            } catch (Exception ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }


    }//GEN-LAST:event_btbrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbrowse;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JPasswordField pfconfirm;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfdisplayname;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfmobile;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables

    BufferedImage resizephoto(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

}
